repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    sha: v1.1.4
    hooks:
    -   id: forbid-crlf
        exclude: \.csv$
    -   id: forbid-tabs
        exclude: Makefile|\.bat$
-   repo: local
    hooks:
    -   id: rustfmt
        name: rustfmt
        description: 'This hook runs rustfmt, which must be installed.'
        entry: rustfmt
        language: system
        files: \.rs$
