version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-linux
      - build-linux
jobs:
  test-linux:
    docker:
      - image: rust:1.21.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run tests
          command: cargo test
  build-linux:
    docker:
      - image: rust:1.21.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build for release
          command: cargo build --release
      - store_artifacts:
          path: target/release/yorick
